### ISSUE TITLE
Problem with parser.csx using v1.1

### ISSUE THREAD

**Issue by Tasselhoff** [tyranid/CANAPE.Core#5]
It's probably me, but when I load the parser I get the following error:

> C:\Users\dave\Documents\AttackNetProto\SuperFunkyChat>C:\Users\dave\Documents\AttackNetProto\SuperFunkyChat\CANAPE.Core-1.1\CANAPE.Cli\bin\Release\netcoreapp3.0\CANAPE.Cli.exe chapter5_proxy.csx --color
> CANAPE.Cli (c) 2017 James Forshaw, 2014 Context Information Security.
> Error: CANAPE.Net.NetServiceException: Could not start service
>  ---> System.Net.Sockets.SocketException (10048): **_Only one usage of each socket address (protocol/network address/port) is normally permitted._**
>    at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
>    at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
>    at System.Net.Sockets.Socket.Bind(EndPoint localEP)
>    at System.Net.Sockets.TcpListener.Start(Int32 backlog)
>    at System.Net.Sockets.TcpListener.Start()
>    at CANAPE.Net.Listeners.TcpNetworkListener.Start() in C:\Users\dave\Documents\AttackNetProto\SuperFunkyChat\CANAPE.Core-1.1\CANAPE.Net\Listeners\TcpNetworkListener.cs:line 180
>    at CANAPE.Net.ProxyNetworkService.Start() in C:\Users\dave\Documents\AttackNetProto\SuperFunkyChat\CANAPE.Core-1.1\CANAPE.Net\ProxyNetworkService.cs:line 644
>    --- End of inner exception stack trace ---
>    at CANAPE.Net.ProxyNetworkService.Start() in C:\Users\dave\Documents\AttackNetProto\SuperFunkyChat\CANAPE.Core-1.1\CANAPE.Net\ProxyNetworkService.cs:line 649
>    at Submission#0.<<Initialize>>d__0.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at Microsoft.CodeAnalysis.Scripting.ScriptExecutionState.RunSubmissionsAsync[TResult](ImmutableArray`1 precedingExecutors, Func`2 currentExecutor, StrongBox`1 exceptionHolderOpt, Func`2 catchExceptionOpt, CancellationToken cancellationToken)
>    at CANAPE.Cli.EntryPoint.RunScript(String filename, IEnumerable`1 include_dirs, IEnumerable`1 metadata_dirs, IEnumerable`1 args) in C:\Users\dave\Documents\AttackNetProto\SuperFunkyChat\CANAPE.Core-1.1\CANAPE.Cli.Lib\EntryPoint.cs:line 156

For reference, the relevanty part of my proxy is 
```
#load "parser.csx"
using static System.Console;
using static CANAPE.Cli.ConsoleUtils;

var template = new FixedProxyTemplate();
// Local port of 4444, destination 192.068.56.101:12345
template.LocalPort = 4444;
template.Host = "192.168.56.101";
template.Port = 12345;
template.AddLayer<Parser>();
```

(which worked before adding the parser) and the parser is:

```
using CANAPE.Net.Layers;
using System.IO;

class Parser : DataParserNetworkLayer
{
    protected override bool NegotiateProtocol(Stream serverStream, Stream clientStream)
    {
        var client = new DataReader(clientStream);
        var server = new DataWriter(serverStream);
        // Read magic from client and write it to server.
        uint magic = client.ReadUInt32();
        Console.WriteLine("Magic: {0:X}", magic);
        server.WriteUInt32(magic);
        // Return true to signal negotiation was successful.
        return true;
    }
}
```

I'd be much obliged if you could let me know where I'm going wrong. Thanks, Dave

Edit: hang on... I tried to go back to the non-parser proxy and I'm getting the same error. Methinks I've messed up somewhere...

Edit 2: I've gone back to the original proxy script and am getting the same error. It looks environmental.

**Comment by Tasselhoff** [comment]
For info, it was because I had an existing terminal open with an instance of the proxy running. Serves me right for having a bazillion things open at the same time!
